import type { Metadata } from 'next'

import './globals.css'

import { ThemeProvider } from '@/providers/theme-provider'

// import AuthProvider from '@/providers/AuthProvider'
import { Toaster } from 'sonner'
import { numericFont, primaryFont } from '@/lib/fonts'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      {/* <AuthProvider> */}
      <body
        className={` ${primaryFont.className} ${numericFont.className} adad min-h-screen antialiased  overflow-x-hidden  `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors position="bottom-left" />
        </ThemeProvider>
      </body>
      {/* </AuthProvider> */}
    </html>
  )
}
